select  ENTIDADE AS COD_CLIENTE, NOME,INSCRICAO_ESTADUAL AS CPF_CNPJ, 
ATIVO AS CADASTRO_ATIVO
from ENTIDADES

--Calculando Valor unitário --
SELECT PRODUTO, 
QUANTIDADE, 
VENDA_BRUTA/QUANTIDADE AS VALOR_UNITARIO,
VENDA_BRUTA
FROM VENDAS_ANALITICAS;

-- Calculando valor do ICMS em R$ e Lucro --

SELECT VENDA_BRUTA, 
ICMS_ALIQUOTA, 
VENDA_BRUTA * ICMS_ALIQUOTA/100 AS IMPOSTO,
VENDA_BRUTA - VENDA_BRUTA * ICMS_ALIQUOTA/100 AS LUCRO 
FROM VENDAS_ANALITICAS;

--Calculando Valor Total de produtos --

SELECT PRODUTO, 
QUANTIDADE,
VALOR_UNITARIO,
VALOR_UNITARIO * QUANTIDADE AS VALOR_TOTAL_PRODUTO,
ICMS_ALIQUOTA,
VALOR_UNITARIO * QUANTIDADE * ICMS_ALIQUOTA/100 AS ICMS_VALOR
FROM 
NF_FATURAMENTO_PRODUTOS;

--Concatenando colunas de cidade e estado e  colocando em upper case --

select ENDERECO, 
CIDADE, 
ESTADO, 
UPPER(CONCAT(CIDADE, '-' ,ESTADO))
from ENDERECOS;

--Concatennando outras campos de tabelas diferentes --

select concat(ENTIDADE, ' - ' ,NOME_FANTASIA) from ENTIDADES




select concat(DESCRICAO, ' -', UNIDADE_MEDIDA) from PRODUTOS

-- Ordenação e concatenação --
select ENTIDADE AS COD_CLIENTE, concat(INSCRICAO_FEDERAL,'-', NOME)
as CLIENTE, DATA_CADASTRO 
from ENTIDADES
ORDER BY DATA_CADASTRO DESC



--Filtrando Valores --

select 
CONCAT(ESPECIE_FISCAL, '-' ,DOCUMENTO_NUMERO) AS DOCUMENTO, 
VENDEDOR, MOVIMENTO, 
PRODUTO, QUANTIDADE, VENDA_BRUTA/QUANTIDADE AS VALOR_UNITARIO
from VENDAS_ANALITICAS
WHERE MOVIMENTO > '01/06/2020'
ORDER BY MOVIMENTO

select 
CONCAT(ESPECIE_FISCAL, '-' ,DOCUMENTO_NUMERO) AS DOCUMENTO, 
VENDEDOR, MOVIMENTO, 
PRODUTO, QUANTIDADE, VENDA_BRUTA, VENDA_BRUTA/QUANTIDADE AS VALOR_UNITARIO
from VENDAS_ANALITICAS
WHERE MOVIMENTO > '01/06/2020' AND PRODUTO = 34912
ORDER BY MOVIMENTO

 --Operadores Like Not like --

SELECT CIDADE, ESTADO
FROM ENDERECOS
where CIDADE LIKE 'S_O%'

SELECT NOME FROM ENTIDADES
WHERE NOME NOT LIKE '%00%'


--Multiplos Filtros -- 

select CLIENTE, QUANTIDADE, VENDEDOR, PRODUTO, MOVIMENTO 
from VENDAS_ANALITICAS
where CLIENTE IN (1876, 1422,2249) AND QUANTIDADE > 0 AND VENDEDOR IN (4,16)
AND PRODUTO NOT IN (34726,34304, 34394, 34593)
ORDER BY MOVIMENTO

--TESTE TÍTULOS A RECEBER --

SELECT MOVIMENTO, ENTIDADE, TITULO, VALOR FROM TITULOS_RECEBER
WHERE MOVIMENTO > '31-12-2019' AND ENTIDADE IN (1874,2308,1520) AND TITULO LIKE '%/1%'
AND (VALOR BETWEEN 150.00 AND 255.23 OR VALOR BETWEEN 425.57 AND 550.12)

--Selecionando os 100 primeiros ordenados pelo valor unitário e tratando os nulos --

SELECT TOP 100 COALESCE(VENDEDOR,-1), PRODUTO, QUANTIDADE,
ROUND(VENDA_BRUTA/QUANTIDADE, 2) AS VALOR_UNITARIO, VENDA_BRUTA
FROM VENDAS_ANALITICAS WHERE VENDEDOR IS NULL 
ORDER BY VALOR_UNITARIO DESC

--Selecionando os não nulos --

SELECT TOP 100 COALESCE(VENDEDOR,-1), 
PRODUTO, QUANTIDADE,
ROUND(VENDA_BRUTA/QUANTIDADE, 2) AS VALOR_UNITARIO, 
VENDA_BRUTA
FROM VENDAS_ANALITICAS WHERE VENDEDOR IS not NULL 
ORDER BY VALOR_UNITARIO DESC

--Manipulando campo de data e data hora --

SELECT NOME,
DATA_CADASTRO,
YEAR(DATA_CADASTRO) AS ANO,
MONTH(DATA_CADASTRO) AS MES,
DAY(DATA_CADASTRO) AS DIA,
DATEPART(WEEKDAY, DATA_CADASTRO) AS DIA_DA_SEMANA,
DATEPART(DAYOFYEAR, DATA_CADASTRO) AS DIA_DO_ANO
FROM ENTIDADES
ORDER BY ANO


--Criando Vencimento para prostestar título e verificando quantos anos o cliente se encontra na base--

select TITULO, VENCIMENTO,
DATEADD(DAY, 10, VENCIMENTO ) AS VENCIMENTO_PARA_PROTESTO,
CONCAT(datediff(year,VENCIMENTO,GETDATE()), ' ANOS') AS DIFERENCA
from TITULOS_RECEBER

select TITULO, 
MOVIMENTO ,
VENCIMENTO,
CONCAT(datediff(DAY, MOVIMENTO, VENCIMENTO), ' DIAS') AS PRAZO,
EOMONTH(MOVIMENTO) AS ULTIMA_DATA_MES,
DAY(EOMONTH(MOVIMENTO) ) AS ULTIMO_DIA_MES
from TITULOS_RECEBER


--Dividir nome do cliente pelo código -- 

SELECT NOME,
charindex(' ', NOME) as POSICAO_DO_ESPACO,
LEN(NOME) AS QUANTIDADE_CARACTERES,
SUBSTRING(NOME, 1, CHARINDEX(' ',NOME)-1) AS NOME_SEM_CÓDIGO,
SUBSTRING(NOME, CHARINDEX(' ', NOME) +1, LEN(NOME)- CHARINDEX(' ', NOME)) AS CODIGO
FROM ENTIDADES


--Dividindo coluna Título em Documento e Parcela, calculando prazo--

SELECT ENTIDADE, 
TITULO, 
SUBSTRING(TITULO, 1, CHARINDEX('/',TITULO)-1) AS DOCUMENTO,
SUBSTRING(TITULO, CHARINDEX('/',TITULO) +1, LEN(TITULO)- CHARINDEX('/',TITULO)) AS PARCELA,
DATEDIFF(DAY,MOVIMENTO,VENCIMENTO) AS PRAZO
FROM TITULOS_RECEBER
WHERE ENTIDADE = 1824
ORDER BY PRAZO DESC



